jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

auth:
  default_login: admin
  default_password: admin
  refresh_token_life_seconds: 60
  access_token_life_seconds: 1

spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml